#!/usr/bin/env python3
"""Generate a headless CodeMender configuration (config.yaml) for CI/CD environments."""

import argparse
import os
from typing import Any, Dict, List, Optional

DEFAULT_SCAN_EXTENSIONS: List[str] = [
    ".py", ".java", ".go", ".js", ".ts", ".c", ".cc", ".cpp", ".h", ".rb", ".php"
]

DEFAULT_EXCLUDE_DIRS: List[str] = [
    "node_modules", "vendor", "dist", "bin", ".git", ".venv", "__pycache__"
]

DEFAULT_EXCLUDE_FILES: List[str] = [
    ".min.js", ".generated.go", ".pb.go"
]


def generate_cm_config(
    model: str = "gemini-3.5-flash",
    output_format: str = "table",
    sandbox_enabled: bool = False,
    sandbox_network_profile: str = "permissive-open",
    extra_extensions: Optional[List[str]] = None,
    extra_exclude_dirs: Optional[List[str]] = None,
    project_paths: Optional[List[str]] = None,
    build_command: str = "",
    project_id: Optional[str] = None,
    location: Optional[str] = None,
) -> Dict[str, Any]:
    """Generate a dictionary structure representing the CodeMender config."""
    scan_exts = list(DEFAULT_SCAN_EXTENSIONS)
    if extra_extensions:
        for ext in extra_extensions:
            if ext not in scan_exts:
                scan_exts.append(ext)

    exclude_dirs = list(DEFAULT_EXCLUDE_DIRS)
    if extra_exclude_dirs:
        for d in extra_exclude_dirs:
            if d not in exclude_dirs:
                exclude_dirs.append(d)

    server_config: Dict[str, Any] = {}
    if project_id:
        server_config["project"] = project_id
    if location:
        server_config["location"] = location

    return {
        "server": server_config,
        "scan": {
            "extensions": {
                "include": scan_exts,
                "exclude": list(DEFAULT_EXCLUDE_FILES),
            },
            "exclude_dirs": exclude_dirs,
            "max_file_size_kb": 500,
            "incremental": True,
        },
        "project_paths": project_paths if project_paths is not None else [],
        "output": {
            "format": output_format,
        },
        "tools": {
            "confirm_commands": False,
            "confirm_writes": False,
            "cleanup_candidate_branches": True,
        },
        "sandbox": {
            "enabled": sandbox_enabled,
            "mounts": {
                "target_dir": ".",
            },
            "network": {
                "profile": sandbox_network_profile,
            },
        },
        "security": {
            "protected_files": [],
        },
        "vcs": {
            "type": "git",
            "commands": {
                "reset": "",
                "diff": "",
                "status": "",
                "stage": "",
            },
        },
        "build": {
            "command": build_command,
        },
        "model": model,
    }


def _format_yaml_list(items: List[str]) -> str:
    """Format a list of strings as a JSON-like YAML inline array."""
    formatted_items = [f'"{item}"' for item in items]
    return f"[{', '.join(formatted_items)}]"


def render_cm_config_yaml(config: Dict[str, Any]) -> str:
    """Render the configuration dictionary into standard YAML string."""
    inc_exts = _format_yaml_list(config["scan"]["extensions"]["include"])
    exc_exts = _format_yaml_list(config["scan"]["extensions"]["exclude"])
    exc_dirs = _format_yaml_list(config["scan"]["exclude_dirs"])
    proj_paths = _format_yaml_list(config.get("project_paths", []))
    sandbox_en = "true" if config["sandbox"]["enabled"] else "false"
    cleanup_br = "true" if config["tools"]["cleanup_candidate_branches"] else "false"

    server_lines = ["server:"]
    if config["server"]:
        if "project" in config["server"]:
            server_lines.append(f'  project: "{config["server"]["project"]}"')
        if "location" in config["server"]:
            server_lines.append(f'  location: "{config["server"]["location"]}"')
    else:
        server_lines[0] = "server: {}"
    server_yaml = "\n".join(server_lines)

    return f"""# CodeMender CI/CD configuration (Generated by setup_cm_config.py)
# Server endpoint and GCP configuration
{server_yaml}

# Code scanning and discovery parameters
scan:
  extensions:
    include: {inc_exts}
    exclude: {exc_exts}
  exclude_dirs: {exc_dirs}
  max_file_size_kb: {config["scan"]["max_file_size_kb"]}
  incremental: true

# Agent file system boundaries (empty = current scan target directory, .codemender, and /tmp)
project_paths: {proj_paths}

# Output format for scan and verify reports
output:
  format: "{config["output"]["format"]}"

# Local tool execution safety guardrails (Headless CI Mode)
tools:
  confirm_commands: false
  confirm_writes: false
  cleanup_candidate_branches: {cleanup_br}

# Sandbox execution parameters (disabled for ephemeral Docker / CI runners)
sandbox:
  enabled: {sandbox_en}
  mounts:
    target_dir: "{config["sandbox"]["mounts"]["target_dir"]}"
  network:
    profile: "{config["sandbox"]["network"]["profile"]}"

# Security boundaries
security:
  protected_files: []

# Version Control System (VCS) Integration
vcs:
  type: "{config["vcs"]["type"]}"
  commands:
    reset: ""
    diff: ""
    status: ""
    stage: ""

# Post-fix verification & regression testing
build:
  command: "{config["build"]["command"]}"

# Backend model intelligence tier
model: "{config["model"]}"
"""


def write_cm_config(
    output_path: str = "~/.codemender/config.yaml",
    model: str = "gemini-3.5-flash",
    output_format: str = "table",
    sandbox_enabled: bool = False,
    sandbox_network_profile: str = "permissive-open",
    extra_extensions: Optional[List[str]] = None,
    extra_exclude_dirs: Optional[List[str]] = None,
    project_paths: Optional[List[str]] = None,
    build_command: str = "",
    project_id: Optional[str] = None,
    location: Optional[str] = None,
    also_write_workspace_config: bool = False,
) -> str:
    """Generate and write the CodeMender config.yaml file to disk."""
    config = generate_cm_config(
        model=model,
        output_format=output_format,
        sandbox_enabled=sandbox_enabled,
        sandbox_network_profile=sandbox_network_profile,
        extra_extensions=extra_extensions,
        extra_exclude_dirs=extra_exclude_dirs,
        project_paths=project_paths,
        build_command=build_command,
        project_id=project_id,
        location=location,
    )
    yaml_content = render_cm_config_yaml(config)

    expanded_output_path = os.path.expanduser(output_path)
    dir_name = os.path.dirname(expanded_output_path)
    if dir_name:
        os.makedirs(dir_name, exist_ok=True)

    with open(expanded_output_path, "w", encoding="utf-8") as f:
        f.write(yaml_content)

    if also_write_workspace_config:
        ws_path = os.path.join(".codemender", "config.yaml")
        os.makedirs(".codemender", exist_ok=True)
        with open(ws_path, "w", encoding="utf-8") as f:
            f.write(yaml_content)

    return expanded_output_path


def main() -> None:
    parser = argparse.ArgumentParser(description="Setup CodeMender headless CI configuration.")
    parser.add_argument("--output", default="~/.codemender/config.yaml", help="Path to config.yaml (e.g. ~/.codemender/config.yaml or .codemender/config.yaml)")
    parser.add_argument("--model", default="gemini-3.5-flash", help="Model intelligence tier")
    parser.add_argument("--format", default="table", choices=["table", "json", "sarif"], help="Output format")
    parser.add_argument("--sandbox", action="store_true", default=False, help="Enable OS sandbox (default: False for CI/Docker runners)")
    parser.add_argument("--network-profile", default="permissive-open", help="Sandbox network profile")
    parser.add_argument("--extra-ext", nargs="*", default=[], help="Extra extensions to include")
    parser.add_argument("--project-paths", nargs="*", default=[], help="Agent allowed file system roots")
    parser.add_argument("--sync-workspace", action="store_true", default=False, help="Also write copy to .codemender/config.yaml")
    parser.add_argument(
        "--project-id",
        default=os.getenv("GCP_PROJECT_ID") or os.getenv("GOOGLE_CLOUD_PROJECT") or "",
        help="Google Cloud Project ID for CodeMender",
    )
    parser.add_argument(
        "--location",
        default=os.getenv("GCP_LOCATION") or "us-central1",
        help="Google Cloud Location for CodeMender",
    )

    args = parser.parse_args()
    written_path = write_cm_config(
        output_path=args.output,
        model=args.model,
        output_format=args.format,
        sandbox_enabled=args.sandbox,
        sandbox_network_profile=args.network_profile,
        extra_extensions=args.extra_ext,
        project_paths=args.project_paths if args.project_paths else None,
        project_id=args.project_id if args.project_id else None,
        location=args.location if args.location else None,
        also_write_workspace_config=args.sync_workspace,
    )
    print(f"CodeMender configuration successfully generated at: {written_path}")


if __name__ == "__main__":
    main()
