#!/usr/bin/env python3
"""Generate a headless CodeMender configuration (config.yaml) for CI/CD environments."""

import argparse
import os
from typing import Any, Dict, List, Optional

DEFAULT_SCAN_EXTENSIONS: List[str] = [
    ".py", ".java", ".go", ".js", ".ts", ".c", ".cc", ".cpp", ".h", ".rb", ".php"
]

DEFAULT_EXCLUDE_DIRS: List[str] = [
    "node_modules", "vendor", "dist", "bin", ".git", ".venv", "__pycache__"
]

DEFAULT_EXCLUDE_FILES: List[str] = [
    ".min.js", ".generated.go", ".pb.go"
]


def generate_cm_config(
    model: str = "gemini-3.5-flash",
    output_format: str = "table",
    sandbox_enabled: bool = False,
    sandbox_network_profile: str = "permissive-open",
    extra_extensions: Optional[List[str]] = None,
    extra_exclude_dirs: Optional[List[str]] = None,
    build_command: str = "",
) -> Dict[str, Any]:
    """Generate a dictionary structure representing the CodeMender config."""
    scan_exts = list(DEFAULT_SCAN_EXTENSIONS)
    if extra_extensions:
        for ext in extra_extensions:
            if ext not in scan_exts:
                scan_exts.append(ext)

    exclude_dirs = list(DEFAULT_EXCLUDE_DIRS)
    if extra_exclude_dirs:
        for d in extra_exclude_dirs:
            if d not in exclude_dirs:
                exclude_dirs.append(d)

    return {
        "server": {},
        "scan": {
            "extensions": {
                "include": scan_exts,
                "exclude": list(DEFAULT_EXCLUDE_FILES),
            },
            "exclude_dirs": exclude_dirs,
            "max_file_size_kb": 500,
            "incremental": True,
        },
        "project_paths": [],
        "output": {
            "format": output_format,
        },
        "tools": {
            "confirm_commands": False,
            "confirm_writes": False,
            "cleanup_candidate_branches": True,
        },
        "sandbox": {
            "enabled": sandbox_enabled,
            "mounts": {
                "target_dir": ".",
            },
            "network": {
                "profile": sandbox_network_profile,
            },
        },
        "security": {
            "protected_files": [],
        },
        "vcs": {
            "type": "git",
            "commands": {
                "reset": "",
                "diff": "",
                "status": "",
                "stage": "",
            },
        },
        "build": {
            "command": build_command,
        },
        "model": model,
    }


def _format_yaml_list(items: List[str]) -> str:
    """Format a list of strings as a JSON-like YAML inline array."""
    formatted_items = [f'"{item}"' for item in items]
    return f"[{', '.join(formatted_items)}]"


def render_cm_config_yaml(config: Dict[str, Any]) -> str:
    """Render the configuration dictionary into standard YAML string."""
    inc_exts = _format_yaml_list(config["scan"]["extensions"]["include"])
    exc_exts = _format_yaml_list(config["scan"]["extensions"]["exclude"])
    exc_dirs = _format_yaml_list(config["scan"]["exclude_dirs"])
    sandbox_en = "true" if config["sandbox"]["enabled"] else "false"
    cleanup_br = "true" if config["tools"]["cleanup_candidate_branches"] else "false"

    return f"""# CodeMender CI/CD configuration (Generated by setup_cm_config.py)
# Server endpoint and build profiles are baked in at build time.
server: {{}}

# Code scanning and discovery parameters
scan:
  extensions:
    include: {inc_exts}
    exclude: {exc_exts}
  exclude_dirs: {exc_dirs}
  max_file_size_kb: {config["scan"]["max_file_size_kb"]}
  incremental: true

# Agent file system boundaries (empty = current scan target directory, .codemender, and /tmp)
project_paths: []

# Output format for scan and verify reports
output:
  format: "{config["output"]["format"]}"

# Local tool execution safety guardrails (Headless CI Mode)
tools:
  confirm_commands: false
  confirm_writes: false
  cleanup_candidate_branches: {cleanup_br}

# Sandbox execution parameters
sandbox:
  enabled: {sandbox_en}
  mounts:
    target_dir: "{config["sandbox"]["mounts"]["target_dir"]}"
  network:
    profile: "{config["sandbox"]["network"]["profile"]}"

# Security boundaries
security:
  protected_files: []

# Version Control System (VCS) Integration
vcs:
  type: "{config["vcs"]["type"]}"
  commands:
    reset: ""
    diff: ""
    status: ""
    stage: ""

# Post-fix verification & regression testing
build:
  command: "{config["build"]["command"]}"

# Backend model intelligence tier
model: "{config["model"]}"
"""


def write_cm_config(
    output_path: str = ".codemender/config.yaml",
    model: str = "gemini-3.5-flash",
    output_format: str = "table",
    sandbox_enabled: bool = False,
    sandbox_network_profile: str = "permissive-open",
    extra_extensions: Optional[List[str]] = None,
    extra_exclude_dirs: Optional[List[str]] = None,
    build_command: str = "",
) -> str:
    """Generate and write the CodeMender config.yaml file to disk."""
    config = generate_cm_config(
        model=model,
        output_format=output_format,
        sandbox_enabled=sandbox_enabled,
        sandbox_network_profile=sandbox_network_profile,
        extra_extensions=extra_extensions,
        extra_exclude_dirs=extra_exclude_dirs,
        build_command=build_command,
    )
    yaml_content = render_cm_config_yaml(config)

    dir_name = os.path.dirname(output_path)
    if dir_name:
        os.makedirs(dir_name, exist_ok=True)

    with open(output_path, "w", encoding="utf-8") as f:
        f.write(yaml_content)

    return output_path


def main() -> None:
    parser = argparse.ArgumentParser(description="Setup CodeMender headless CI configuration.")
    parser.add_argument("--output", default=".codemender/config.yaml", help="Path to config.yaml")
    parser.add_argument("--model", default="gemini-3.5-flash", help="Model intelligence tier")
    parser.add_argument("--format", default="table", choices=["table", "json", "sarif"], help="Output format")
    parser.add_argument("--sandbox", action="store_true", default=False, help="Enable OS sandbox")
    parser.add_argument("--network-profile", default="permissive-open", help="Sandbox network profile")
    parser.add_argument("--extra-ext", nargs="*", default=[], help="Extra extensions to include")

    args = parser.parse_args()
    written_path = write_cm_config(
        output_path=args.output,
        model=args.model,
        output_format=args.format,
        sandbox_enabled=args.sandbox,
        sandbox_network_profile=args.network_profile,
        extra_extensions=args.extra_ext,
    )
    print(f"CodeMender configuration successfully generated at: {written_path}")


if __name__ == "__main__":
    main()
